### ISSUE TITLE
Mask Textures do not import

### ISSUE THREAD

**Issue by Surasia** [Coreforge/blender-halo-infinite#2]
Textures such as __chore\pc__\levels\multi\sgh_blueprint\masktextures\tmp_pipemother_floor_lower_a don't import as they are 64x64, 128x128 or 256x256

Most of these still have their chunk files, but the blender importer throws an error about not being able to find their width/height.

`Python: Traceback (most recent call last):
  File "C:\Users\NAME\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-halo-infinite-dev\TextureOp.py", line 44, in execute
    tex.readTexture(self.filepath,name,settings)
  File "C:\Users\NAME\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-halo-infinite-dev\Texture.py", line 476, in readTexture
    img.pixels = self.readTextureData(img_data,width,height,import_settings,format)
ValueError: bpy_struct: item.attr = val: sequence expected at dimension 1, not 'NoneType'

location: <unknown location>:-1

`

**Comment by Coreforge** [comment]
Which textures exactly don't work?
- __chore/pc__/levels/multi/sgh_blueprint/masktextures/tmp_pipemother_floor_lower_a/default_layer_off_mask_4ko8zxns2q{pc}.bitmap
- __chore/pc__/levels/multi/sgh_blueprint/masktextures/tmp_pipemother_floor_lower_a/default_layers1_&_2_&_3_mask_4ko825bmf7{pc}.bitmap
- __chore/pc__/levels/multi/sgh_blueprint/masktextures/tmp_pipemother_floor_lower_a/default_layers1_&_2_&_3_mask_4ko825bmf7_v2{pc}.bitmap
- __chore/pc__/levels/multi/sgh_blueprint/masktextures/tmp_pipemother_floor_lower_a/default_layer_off_mask_4ko8mx2toz{pc}.bitmap

all import fine for me, the other ones in that folder don't because I haven't added that format yet (I just add formats when I come across textures that use them).

**Comment by Surasia** [comment]
That BC3 fix worked for me- thanks!
